import {multiplayer} from './multiplayer.js';
import {catalog,makeVehicle} from './garage.js';
import * as T from './three.module.js';
const $=id=>document.getElementById(id), scene=new T.Scene();scene.background=new T.Color('#a6c5ba');scene.fog=new T.Fog('#a6c5ba',110,340);
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('uploadNote').textContent='Для игры нужен браузер с поддержкой WebGL. Попробуй Chrome или Safari.';$('start').disabled=true;throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;$('world').appendChild(renderer.domElement);const camera=new T.PerspectiveCamera(55,1,.1,700);scene.add(new T.HemisphereLight('#ecffed','#546b39',2.7));const sun=new T.DirectionalLight('#fff5d7',3);sun.position.set(50,110,40);scene.add(sun);
const mat=(c)=>new T.MeshStandardMaterial({color:c,roughness:.88});const grass=mat('#60834d'),asphalt=mat('#3e4947'),cream=mat('#eae7d6'),red=mat('#de6954'),dark=mat('#172a26');
function box(w,h,d,m,x,y,z){const a=new T.Mesh(new T.BoxGeometry(w,h,d),m);a.position.set(x,y,z);scene.add(a);return a;}
box(1400,.4,1400,grass,0,-.3,0);
const pts=[[-75,65],[-75,-45],[-45,-72],[-20,-55],[-30,-15],[4,-3],[35,-42],[70,-25],[77,18],[42,43],[17,19],[-8,52],[-25,91],[-62,100]].map(([x,z])=>new T.Vector3(x,0,z));const curve=new T.CatmullRomCurve3(pts,true,'catmullrom',.4),N=700,roadWidth=13;const samples=Array.from({length:N},(_,i)=>curve.getPointAt(i/N));
function ribbon(offset,width,materials){const pos=[],idx=[],geo=new T.BufferGeometry();for(let i=0;i<=N;i++){let p=curve.getPointAt((i%N)/N),t=curve.getTangentAt((i%N)/N),n=new T.Vector3(t.z,0,-t.x);for(const d of [offset-width/2,offset+width/2])pos.push(p.x+n.x*d,.03,p.z+n.z*d);if(i<N){let j=i*2;idx.push(j,j+2,j+1,j+1,j+2,j+3);geo.addGroup(i*6,6,materials.length>1?Math.floor(i/4)%2:0);}}geo.setAttribute('position',new T.Float32BufferAttribute(pos,3));geo.setIndex(idx);geo.computeVertexNormals();const mesh=new T.Mesh(geo,materials);scene.add(mesh);return mesh;}ribbon(0,roadWidth,[asphalt]);ribbon(-7,.9,[red,cream]);ribbon(7,.9,[red,cream]);ribbon(-6,.12,[cream]);ribbon(6,.12,[cream]);
for(let i=0;i<N;i+=9){const p=samples[i],t=curve.getTangentAt(i/N);for(const side of [-1,1]){const wall=box(.35,.8,5.5,cream,p.x+t.z*side*11,.4,p.z-t.x*side*11);wall.rotation.y=Math.atan2(t.x,t.z);}}
let seed=18;function rand(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646;}
for(let i=0;i<190;i++){let x=rand()*340-170,z=rand()*350-140;if(samples.some(p=>(p.x-x)**2+(p.z-z)**2<300))continue;const h=4+rand()*8;const tree=new T.Mesh(new T.ConeGeometry(2.5+h*.15,h,5),mat(['#315d3e','#416c43','#254f3e'][i%3]));tree.position.set(x,h/2,z);scene.add(tree);}
const startPoint=curve.getPointAt(0),startTan=curve.getTangentAt(0),startAngle=Math.atan2(startTan.x,startTan.z);for(let x=0;x<10;x++)for(let z=0;z<2;z++){const tile=box(1.3,.04,1.2,(x+z)%2?cream:dark,startPoint.x+(x-4.5)*1.3,.07,startPoint.z+z*1.2);tile.rotation.y=startAngle;}
let {car,wheels}=makeVehicle('formula');scene.add(car);const shadow=new T.Mesh(new T.CircleGeometry(2.6,24),new T.MeshBasicMaterial({color:'#192b20',transparent:true,opacity:.22,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.06;scene.add(shadow);
let mode='garage',speed=0,heading=startAngle,elapsed=0,progress=0,nearest=0,countdown=0,gas=false,brake=false,steering=0,pausedFrom='race';let uploaded=[];const keys=new Set();const mapctx=$('map').getContext('2d');
function resetCar(){car.position.copy(samples[0]);heading=startAngle;car.rotation.y=heading;speed=0;nearest=0;progress=0;elapsed=0;}
resetCar();
let selected='formula';
function choose(id){if(mode!=='garage'||!catalog.some(v=>v.id===id))return;scene.remove(car);car.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();});({car,wheels}=makeVehicle(id));scene.add(car);selected=id;resetCar();$('carName').textContent=catalog.find(v=>v.id===id).name;$('uploadNote').textContent=catalog.find(v=>v.id===id).detail;for(const b of $('carChoices').children)b.setAttribute('aria-pressed',String(b.dataset.id===id));try{localStorage.setItem('garage-car',id);}catch{}}
for(const item of catalog){const b=document.createElement('button');b.className='car-choice';b.dataset.id=item.id;b.style.setProperty('--car-color',item.color);b.textContent=item.name;b.setAttribute('aria-pressed',String(item.id===selected));b.onclick=()=>choose(item.id);$('carChoices').appendChild(b);}
try{choose(localStorage.getItem('garage-car')||'formula');}catch{choose('formula');}
function inputsOff(){gas=brake=false;steering=0;keys.clear();$('knob').style.transform='';for(const id of ['gas','brake'])$(id).classList.remove('active');}
function setVisible(race){$('intro').hidden=race;$('hint').hidden=race;for(const id of ['hud','controls','speed','pause'])$(id).hidden=!race;$('mode').hidden=race;}
function start(){inputsOff();resetCar();setVisible(true);$('overlay').hidden=true;countdown=3;mode='countdown';$('message').style.fontSize='60px';return{status:mode};}
function pause(){if(!['race','countdown'].includes(mode))return;pausedFrom=mode;mode='paused';inputsOff();$('overlayLabel').textContent='ПИТ-СТОП';$('overlayTitle').textContent='Пауза';$('overlayText').textContent='Трасса подождёт.';$('resume').hidden=false;$('overlay').hidden=false;$('message').textContent='';}
function finish(){mode='finished';inputsOff();$('overlayLabel').textContent='КРУГ ЗАВЕРШЁН';$('overlayTitle').textContent='Вот это рисунок!';$('overlayText').textContent='Твоё время — '+format(elapsed);$('resume').hidden=true;$('overlay').hidden=false;}
$('start').onclick=start;$('restart').onclick=()=>net.active()?net.rematch():start();$('pause').onclick=pause;$('resume').onclick=()=>{mode=pausedFrom;$('overlay').hidden=true;};$('garage').onclick=()=>{if(net.active()){net.leave();return;}mode='garage';inputsOff();resetCar();setVisible(false);$('overlay').hidden=true;$('message').textContent='';};
function pedal(id,fn){const el=$(id);el.onpointerdown=e=>{e.preventDefault();el.setPointerCapture(e.pointerId);fn(true);el.classList.add('active');};const release=()=>{fn(false);el.classList.remove('active');};el.onpointerup=release;el.onpointercancel=release;el.onlostpointercapture=release;}pedal('gas',v=>gas=v);pedal('brake',v=>brake=v);
let steerPointer=null;function moveSteer(e){if(e.pointerId!==steerPointer)return;const r=$('steer').getBoundingClientRect();steering=T.MathUtils.clamp((e.clientX-r.left-r.width/2)/(r.width*.35),-1,1);$('knob').style.transform=`translateX(${steering*37}px)`;}$('steer').onpointerdown=e=>{e.preventDefault();steerPointer=e.pointerId;$('steer').setPointerCapture(e.pointerId);moveSteer(e);};$('steer').onpointermove=moveSteer;for(const event of ['onpointerup','onpointercancel','onlostpointercapture'])$('steer')[event]=()=>{steerPointer=null;steering=0;$('knob').style.transform='';};
window.addEventListener('keydown',e=>{if(mode==='garage'||['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(e.key==='Escape')pause();});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{inputsOff();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){inputsOff();pause();}});
function format(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${(s%60).toFixed(1).padStart(4,'0')}`;}
function miniMap(){const c=mapctx;c.clearRect(0,0,180,130);c.lineWidth=5;c.strokeStyle='#b5c5ac';c.beginPath();samples.forEach((p,i)=>{const x=(p.x+90)*.94+8,y=(p.z+85)*.59+6;i?c.lineTo(x,y):c.moveTo(x,y);});c.closePath();c.stroke();c.fillStyle='#d9ff65';c.beginPath();c.arc((car.position.x+90)*.94+8,(car.position.z+85)*.59+6,5,0,Math.PI*2);c.fill();}
let previous=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-previous)/1000,.04);previous=now;if(mode==='countdown'){countdown-=dt;$('message').textContent=countdown>0?Math.ceil(countdown):'ВПЕРЁД';if(countdown<0){mode='race';$('message').textContent='';}}if(mode==='race'){elapsed+=dt;const throttle=gas||keys.has('w')||keys.has('arrowup'),stop=brake||keys.has('s')||keys.has('arrowdown');let turn=steering+(keys.has('a')||keys.has('arrowleft')?-1:0)+(keys.has('d')||keys.has('arrowright')?1:0);turn=T.MathUtils.clamp(turn,-1,1);speed=T.MathUtils.clamp(speed+(throttle?12:-3)*dt-(stop?28*dt:0),0,36);heading-=turn*Math.min(speed/8,1)*1.6*dt;car.position.x+=Math.sin(heading)*speed*dt;car.position.z+=Math.cos(heading)*speed*dt;let best=Infinity,next=nearest;for(let j=0;j<N;j++){const d=car.position.distanceToSquared(samples[j]);if(d<best){best=d;next=j;}}let delta=next-nearest;if(delta>N/2)delta-=N;if(delta<-N/2)delta+=N;if(best<100&&Math.abs(delta)<12)progress+=delta;nearest=next;if(progress>=N-3&&elapsed>10)finish();}
for(const o of opponents.values()){o.car.position.lerp(o.target,1-Math.exp(-12*dt));let d=o.heading-o.car.rotation.y;d=Math.atan2(Math.sin(d),Math.cos(d));o.car.rotation.y+=d*(1-Math.exp(-12*dt));}car.rotation.y=heading;shadow.position.x=car.position.x;shadow.position.z=car.position.z;wheels.forEach(w=>w.rotation.x+=speed*dt*2);if(mode==='garage'){const t=now*.00018;camera.position.set(car.position.x+Math.cos(t)*9,5.7,car.position.z+Math.sin(t)*9);camera.lookAt(car.position.x,-.1,car.position.z);}else{const target=new T.Vector3(car.position.x-Math.sin(heading)*10,7,car.position.z-Math.cos(heading)*10);camera.position.lerp(target,1-Math.exp(-5*dt));camera.lookAt(car.position.x+Math.sin(heading)*5,1,car.position.z+Math.cos(heading)*5);}$('speedValue').textContent=Math.round(speed*3.6);$('time').textContent=format(elapsed);miniMap();renderer.render(scene,camera);}
function resize(){const r=$('world').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}window.addEventListener('resize',resize);resize();requestAnimationFrame(frame);
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'start_time_trial',description:'Начать заново одиночный заезд на один круг.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(input===null||typeof input!=='object'||Object.keys(input).length)throw Error('Expected empty object');return start();}});}catch(e){console.warn('Agent controls unavailable');}}

const opponents=new Map();
function clearOpponents(){for(const o of opponents.values()){scene.remove(o.car);o.car.traverse(x=>{x.geometry?.dispose();if(x.material)for(const m of Array.isArray(x.material)?x.material:[x.material])m.dispose();});}opponents.clear();}
const net=multiplayer({getCar:()=>selected,getState:()=>({x:car.position.x,z:car.position.z,heading,speed,progress,finished:mode==='finished'}),onRace:(seconds,slot)=>{start();countdown=seconds;const t=curve.getTangentAt(0);car.position.x+=t.z*((slot%3)-1)*3-t.x*Math.floor(slot/3)*5;car.position.z-=t.x*((slot%3)-1)*3+t.z*Math.floor(slot/3)*5;},onLobby:()=>{mode='garage';inputsOff();resetCar();setVisible(false);$('overlay').hidden=true;$('message').textContent='';$('online').open=true;},onDisconnect:clearOpponents,onSnapshot:(room,myId)=>{const ids=new Set(room.players.filter(p=>p.id!==myId).map(p=>p.id));for(const [id,o] of opponents)if(!ids.has(id)){scene.remove(o.car);opponents.delete(id);}for(const p of room.players){if(p.id===myId)continue;let o=opponents.get(p.id);if(o&&o.type!==p.car){scene.remove(o.car);opponents.delete(p.id);o=null;}if(!o){o={...makeVehicle(p.car),type:p.car,target:new T.Vector3(),heading:0};scene.add(o.car);opponents.set(p.id,o);}o.car.visible=room.phase==='race'&&p.positioned;if(o.car.visible){o.target.set(p.x,0,p.z);o.heading=p.heading;if(o.car.position.lengthSq()===0)o.car.position.copy(o.target);}}}});
