export function multiplayer({getCar,onRace,onLobby,getState,onSnapshot,onDisconnect}){
const $=id=>document.getElementById(id);let session=null,room=null,busy=false,lastSuccess=0,raceStart=0,ready=false,lastLobbySignature='';
let shareBase=location.origin;fetch('/api/connection',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(r=>r.json()).then(d=>{if(['localhost','127.0.0.1'].includes(location.hostname)&&d.lanUrl)shareBase=d.lanUrl;}).catch(()=>{});
const codeFromLink=new URL(location.href).searchParams.get('room');if(codeFromLink){$('roomCode').value=codeFromLink.toUpperCase();$('online').open=true;$('createRoom').hidden=true;}try{$('driverName').value=localStorage.getItem('driver-name')||'Гонщик';}catch{}
function notice(s){$('netNotice').textContent=s;}
async function api(action,extra={}){const r=await fetch('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...session,...extra}),signal:AbortSignal.timeout(5000)});let result;try{result=await r.json();}catch{throw Error('Открой игру по адресу сервера для совместной игры.');}if(!r.ok)throw Object.assign(Error(result.error||'Сервер недоступен'),{status:r.status});return result;}
function render(data){room=data;const me=data.players.find(p=>p.id===session.id);ready=!!me?.ready;$('roomSetup').hidden=true;$('roomLobby').hidden=false;$('roomTitle').textContent='КОМНАТА '+data.code+' · '+data.players.length+'/5';const signature=JSON.stringify(data.players.map(p=>[p.id,p.name,p.ready,p.finished,data.host]));if(signature!==lastLobbySignature){lastLobbySignature=signature;$('playerList').replaceChildren();for(const p of data.players){const li=document.createElement('li');li.textContent=p.name+(p.id===session.id?' (ты)':'')+(p.id===data.host?' · хозяин':'')+' — '+(p.finished?'финиш':p.ready?'готов':'выбирает');$('playerList').appendChild(li);}}$('ready').textContent=ready?'Отменить готовность':'Я готов';$('launch').hidden=data.host!==session.id;$('launch').disabled=data.players.length<2||!data.players.every(p=>p.ready);$('ready').hidden=data.phase!=='lobby';$('launch').hidden||=data.phase!=='lobby';$('start').hidden=true;$('netHud').hidden=false;$('netHud').textContent=data.players.filter(p=>p.finished).length+' на финише · '+data.players.length+' игроков';onSnapshot(data,session.id);if(data.phase==='race'&&raceStart!==data.startAt){raceStart=data.startAt;onRace(Math.max(0,(data.startAt-data.now)/1000),data.players.findIndex(p=>p.id===session.id));}if(data.phase==='lobby'&&raceStart){raceStart=0;onLobby();}lastSuccess=Date.now();}
async function enter(action){$('createRoom').disabled=$('joinRoom').disabled=true;notice('Подключение…');try{const d=await api(action,{name:$('driverName').value,car:getCar(),code:$('roomCode').value.trim()});try{localStorage.setItem('driver-name',$('driverName').value);}catch{}session={id:d.id,token:d.token,code:d.code};raceStart=0;render(d);const u=new URL(location.href);u.searchParams.set('room',d.code);history.replaceState(null,'',u);notice('Отправь ссылку друзьям и дождись готовности.');}catch(e){notice(e.message);}finally{$('createRoom').disabled=$('joinRoom').disabled=false;}}
$('createRoom').onclick=()=>enter('create');$('joinRoom').onclick=()=>enter('join');$('ready').onclick=async()=>{try{render(await api('ready',{ready:!ready,car:getCar()}));}catch(e){notice(e.message);}};$('launch').onclick=async()=>{try{render(await api('start'));}catch(e){notice(e.message);}};
$('copyRoom').onclick=async()=>{const link=new URL('/',shareBase);link.searchParams.set('room',session.code);try{if(navigator.share){await navigator.share({title:'Бумажный Гран-при',text:'Выбирай машинку — устроим гонку!',url:link.href});notice('Приглашение готово');}else{await navigator.clipboard.writeText(link.href);notice('Ссылка скопирована');}}catch{$('shareLink').hidden=false;$('shareLink').value=link.href;$('shareLink').select();notice('Скопируй ссылку из поля');}};
async function leave(){if(session)try{await api('leave');}catch{}session=null;room=null;raceStart=0;$('createRoom').hidden=false;$('roomSetup').hidden=false;$('roomLobby').hidden=true;$('start').hidden=false;$('netHud').hidden=true;onDisconnect();onLobby();const u=new URL(location.href);u.searchParams.delete('room');history.replaceState(null,'',u);notice('');}
$('leaveRoom').onclick=leave;
setInterval(async()=>{if(!session||busy)return;busy=true;try{render(await api('sync',{car:getCar(),state:raceStart?getState():null}));if(Date.now()-lastSuccess<1000&&$('netNotice').textContent.startsWith('Связь'))notice('');}catch(e){notice('Связь прервана: '+e.message);$('netHud').textContent='Нет связи с сервером';if(e.status===401||e.status===404)await leave();}finally{busy=false;}},100);
return {active:()=>!!session,use:async()=>{try{render(await api('use'));}catch(e){notice(e.message);}},leave,rematch:async()=>{if(!session)return;try{render(await api('rematch'));}catch(e){$('overlayText').textContent=e.message;}}};
}
