import {track,trackLength} from './track-data.js';
export const LAPS=3, FINISH=track.length*LAPS;
export const pickups=Array.from({length:Math.floor(trackLength/100)},(_,i)=>{const index=Math.round((i+1)*100/trackLength*track.length)%track.length;return{id:i,index,...track[index]};});
export function roadPosition(x,z){let index=0,distance=Infinity;for(let i=0;i<track.length;i++){const d=(x-track[i].x)**2+(z-track[i].z)**2;if(d<distance){distance=d;index=i;}}const d=Math.sqrt(distance),limit=4.6;return {index,distance:d,x:d>limit?track[index].x+(x-track[index].x)*limit/d:x,z:d>limit?track[index].z+(z-track[index].z)*limit/d:z};}
export function initPowers(p){Object.assign(p,{ability:null,boostUntil:0,slowUntil:0,shootUntil:0,nextShot:0,pickupLocks:{}});}
export function collect(p,now){if(p.ability||p.finished)return;for(const item of pickups){if((p.pickupLocks[item.id]||0)>now)continue;if(Math.hypot(p.x-item.x,p.z-item.z)<5.5){p.ability=['gun','rocket','boost'][Math.floor(Math.random()*3)];p.pickupLocks[item.id]=now+8000;return;}}}
export function usePower(p,world,now){if(!p.ability||p.finished)return false;const kind=p.ability;p.ability=null;if(kind==='boost')p.boostUntil=now+3000;else if(kind==='gun'){p.shootUntil=now+3000;p.nextShot=now;}else spawn(p,world,'rocket',now);return true;}
function spawn(p,world,kind,now){const dx=Math.sin(p.heading),dz=Math.cos(p.heading);world.projectiles.push({id:++world.sequence,owner:p.id,kind,x:p.x+dx*3,z:p.z+dz*3,dx,dz,born:now,last:now});}
export function tickPowers(world,players,now){for(const p of players){if(p.shootUntil>now&&now>=p.nextShot&&!p.finished){spawn(p,world,'bullet',now);p.nextShot=now+170;}}world.projectiles=world.projectiles.filter(s=>{const dt=Math.min(.1,Math.max(0,(now-s.last)/1000));s.last=now;const oldX=s.x,oldZ=s.z;const velocity=s.kind==='rocket'?65:100;s.x+=s.dx*velocity*dt;s.z+=s.dz*velocity*dt;if(now-s.born>(s.kind==='rocket'?2500:1000))return false;for(const p of players){if(p.id===s.owner||p.finished||!p.positioned)continue;const ax=s.x-oldX,az=s.z-oldZ,t=Math.max(0,Math.min(1,((p.x-oldX)*ax+(p.z-oldZ)*az)/(ax*ax+az*az||1)));if(Math.hypot(p.x-oldX-ax*t,p.z-oldZ-az*t)<1.8){p.slowUntil=Math.max(p.slowUntil||0,now+(s.kind==='rocket'?2200:600));return false;}}return true;});}
