import {roadPosition,initPowers,collect,usePower,tickPowers} from './dist/race-rules.js';
import http from 'node:http';
import os from 'node:os';
import {readFile} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import {randomBytes} from 'node:crypto';
const root=resolve('dist'),rooms=new Map(),port=Number(process.env.PORT||8766);
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.jpg':'image/jpeg'};
const cars=new Set(['formula','luxury','micro','classic','hatch','police']);
function fail(status,message){throw Object.assign(Error(message),{status});}
function snapshot(room){return {code:room.code,phase:room.phase,startAt:room.startAt,now:Date.now(),host:room.host,projectiles:room.projectiles,players:[...room.players.values()].map(({token,lastSeen,pickupLocks,...p})=>p)};}
function clean(room){const now=Date.now();for(const [id,p] of room.players)if(now-p.lastSeen>15000)room.players.delete(id);if(!room.players.has(room.host))room.host=room.players.keys().next().value;if(!room.players.size)rooms.delete(room.code);}
const server=http.createServer(async(req,res)=>{const json=(status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/health')return json(200,{ok:true});if(url.pathname.startsWith('/api/')){if(req.method!=='POST')fail(405,'Нужен POST');if(req.headers.origin&&new URL(req.headers.origin).host!==req.headers.host)fail(403,'Запрос с другого сайта запрещён');let data='',n=0;for await(const chunk of req){n+=chunk.length;if(n>8192)fail(413,'Слишком большой запрос');data+=chunk;}let b;try{b=JSON.parse(data||'{}');}catch{fail(400,'Некорректный запрос');}if(!b||typeof b!=='object')fail(400,'Некорректный запрос');const action=url.pathname.slice(5);if(action==='connection'){if(process.env.NODE_ENV==='production')return json(200,{lanUrl:null});const entries=Object.entries(os.networkInterfaces());const candidates=entries.filter(([name])=>/^(en|eth|wlan)/.test(name)).flatMap(([,a])=>a).filter(a=>a.family==='IPv4'&&!a.internal);const ip=candidates[0]?.address;return json(200,{lanUrl:ip?'http://'+ip+':'+port:null});}
if(action==='create'||action==='join'){let room;if(action==='create'){if(rooms.size>100)fail(503,'Сервер занят');let code;do{code=randomBytes(3).toString('hex').toUpperCase();}while(rooms.has(code));room={code,players:new Map(),host:null,phase:'lobby',startAt:0,projectiles:[],sequence:0};rooms.set(code,room);}else{room=rooms.get(String(b.code||'').toUpperCase());if(!room)fail(404,'Комната не найдена');clean(room);if(room.phase!=='lobby')fail(409,'Заезд уже начался. Дождись нового заезда.');}if(room.players.size>=5)fail(409,'В комнате уже 5 игроков');if(!cars.has(b.car))fail(400,'Выбери машину');const id=randomBytes(8).toString('hex'),token=randomBytes(24).toString('hex');const p={id,token,name:String(b.name||'Гонщик').trim().slice(0,20)||'Гонщик',car:b.car,ready:false,lastSeen:Date.now(),x:0,z:0,heading:0,speed:0,progress:0,finished:false,time:null,positioned:false};initPowers(p);room.players.set(id,p);room.host??=id;return json(200,{id,token,...snapshot(room)});}
const room=rooms.get(String(b.code||'').toUpperCase());if(!room)fail(404,'Комната закрыта');clean(room);const p=[...room.players.values()].find(p=>p.token===b.token);if(!p)fail(401,'Соединение потеряно. Зайди в комнату снова.');p.lastSeen=Date.now();if(action==='leave'){room.players.delete(p.id);clean(room);return json(200,{ok:true});}
if(action==='ready'){if(room.phase!=='lobby')fail(409,'Заезд уже начался');p.ready=!!b.ready;if(cars.has(b.car))p.car=b.car;}
else if(action==='start'){if(p.id!==room.host)fail(403,'Стартует создатель комнаты');if(room.phase!=='lobby')fail(409,'Заезд уже начался');if(room.players.size<2)fail(409,'Нужно хотя бы 2 игрока');if([...room.players.values()].some(p=>!p.ready))fail(409,'Дождись готовности всех игроков');room.phase='race';room.startAt=Date.now()+4000;}
else if(action==='use'){if(room.phase!=='race'||Date.now()<room.startAt)fail(409,'Дождись старта');usePower(p,room,Date.now());}
else if(action==='rematch'){if(p.id!==room.host)fail(403,'Новый заезд создаёт хозяин комнаты');room.phase='lobby';room.startAt=0;room.projectiles=[];for(const p of room.players.values()){initPowers(p);p.ready=false;p.positioned=false;p.finished=false;p.time=null;p.progress=0;}}
else if(action==='sync'){if(cars.has(b.car)&&room.phase==='lobby'){if(p.car!==b.car)p.ready=false;p.car=b.car;}if(room.phase==='race'&&b.state){const s=b.state;if(!['x','z','heading','speed','progress'].every(k=>typeof s[k]==='number'&&Number.isFinite(s[k])))fail(400,'Некорректное положение');const bounded=roadPosition(s.x,s.z);p.x=bounded.x;p.z=bounded.z;p.heading=s.heading%(Math.PI*2);p.speed=Math.max(0,Math.min(p.boostUntil>Date.now()?54:36,s.speed));p.progress=Math.max(0,Math.min(2100,s.progress));p.positioned=true;if(Date.now()>=room.startAt)collect(p,Date.now());if(s.finished&&!p.finished&&Date.now()-room.startAt>10000&&p.progress>=2100){p.finished=true;p.time=(Date.now()-room.startAt)/1000;}}}
else fail(404,'Действие не найдено');return json(200,snapshot(room));}
if(req.method!=='GET'&&req.method!=='HEAD')fail(405,'Метод недоступен');let file=resolve(root,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root+sep))fail(403,'Доступ запрещён');let buffer;try{buffer=await readFile(file);}catch{fail(404,'Файл не найден');}res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(req.method==='HEAD'?undefined:buffer);
}catch(e){if(!res.headersSent)json(e.status||500,{error:e.status?e.message:'Ошибка сервера'});else res.end();}});
setInterval(()=>{for(const r of rooms.values())clean(r);},10000).unref();
setInterval(()=>{const now=Date.now();for(const r of rooms.values())if(r.phase==='race'&&now>=r.startAt)tickPowers(r,[...r.players.values()],now);},50).unref();server.listen(port,'0.0.0.0',()=>console.log(`Race server: http://localhost:${port}`));
